packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  msw: true
  playwright: true
  prisma: true
  sharp: true
  unrs-resolver: true
