packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
