// All user-facing intake copy lives here so wording can change without
// touching catalog logic, validation or the modal.

export const BRIEF_STEP_COPY = {
  about: { title: "About your product", description: "The basics we build everything else on." },
  goal: { title: "Goal and audience", description: "Who the site is for and what it should get them to do." },
  product: { title: "Product details", description: "What it does, how it works and what it costs." },
  cta: { title: "Call to action", description: "Where visitors go when they are ready." },
  brand: { title: "Brand and style", description: "Preferences we pass to the design step." },
  proof: { title: "Proof", description: "Only add things you can back up. We never make these up for you." },
  presence: { title: "Contact and legal", description: "Links and details for the footer and legal pages." },
  visitors: { title: "Visitors", description: "Where your traffic comes from and what they search for." },
} as const

export const BRIEF_FIELD_COPY = {
  productName: { label: "Product name", help: "Used for: your logo text, page title and headline.", example: "Ledgerly" },
  companyName: { label: "Company name", help: "Used for: the footer and legal pages. Leave blank if it matches the product name.", example: "Ledgerly Labs Inc." },
  oneLiner: { label: "What does it do?", help: "Used for: your headline and hero section. One or two plain sentences.", example: "Ledgerly turns bank exports into tidy monthly books for freelancers." },
  productType: { label: "What kind of product is it?", help: "Used for: picking the right page structure." },
  availability: { label: "Can people use it today?", help: "Used for: the main button and launch messaging." },
  launchDate: { label: "Launch date", help: "Used for: a launch countdown or date mention." },
  existingUrl: { label: "Your current website or product link", help: "Used for: reading what you already have. Optional.", example: "https://ledgerly.app" },
  niche: { label: "Category", help: "Used for: choosing research for your industry. We classify it if you skip." },
  primaryGoal: { label: "Main goal of the site", help: "Used for: the main call to action. Pick one." },
  audienceDescription: { label: "Who is the ideal customer?", help: "Used for: tone, examples and design research.", example: "Freelance designers who hate bookkeeping" },
  audienceSegment: { label: "Business or consumer?", help: "Used for: tone and proof style." },
  audienceDetails: { label: "More about the audience", help: "Used for: tailoring examples and research. All optional." },
  buyer: { label: "Who pays?", help: "Used for: speaking to the decision maker when the buyer is not the user." },
  problem: { label: "What problem does it solve?", help: "Used for: the problem and benefits sections. Concrete examples help.", example: "Freelancers lose a weekend every quarter matching receipts to bank lines." },
  valueProp: { label: "Main benefit in one line", help: "Used for: the hero subheadline.", example: "Books done in minutes, not weekends." },
  siteType: { label: "Site size", help: "Used for: one long page or several pages." },
  language: { label: "Site language", help: "Used for: all generated copy." },
  features: { label: "Key features", help: "Used for: the features section. First one is the most important.", example: "Auto-categorise bank lines" },
  howItWorks: { label: "How it works", help: "Used for: the how-it-works section." },
  differentiators: { label: "What makes it different?", help: "Used for: comparison and benefit copy." },
  competitors: { label: "Competitors", help: "Used for: research only. Names never appear on your site unless you allow comparison." },
  currentAlternative: { label: "What do customers use today?", help: "Used for: problem framing.", example: "Spreadsheets and a shoebox of receipts" },
  allowCompetitorComparison: { label: "Allow a comparison with competitors on the site", help: "Off by default. When off, competitor names never appear in your copy." },
  pricing: { label: "Pricing", help: "Used for: the pricing section. We never guess prices. Leave blank to hide pricing." },
  ctaPrimary: { label: "Main button", help: "Used for: every main call-to-action button." },
  ctaSecondary: { label: "Second button", help: "Used for: a lower-commitment option next to the main button." },
  contactEmail: { label: "Contact email", help: "Used for: email buttons and the contact section." },
  showContactPublicly: { label: "Show this email on the site", help: "When on, the email is visible to every visitor." },
  afterConversion: { label: "After someone converts", help: "Used for: the thank-you message." },
  logo: { label: "Logo", help: "PNG, JPG or WebP up to 2 MB. Without one we use a text wordmark." },
  brandColors: { label: "Brand colors", help: "Up to 5 hex colors. Preferences only; the design step keeps contrast safe." },
  fontPreference: { label: "Font preference", help: "We pick the closest font we support.", example: "Something like Inter" },
  tone: { label: "Tone of voice", help: "Pick up to two." },
  designReferences: { label: "Sites you like", help: "Up to 3 links. Used as style inspiration, never copied." },
  visualNotes: { label: "Anything else about the look", help: "Used for: design direction.", example: "Calm, lots of white space, no stock photos of handshakes" },
  sourceDocument: { label: "Source document", help: "PDF, DOCX, PPTX, TXT or MD up to 10 MB. Used only to pre-fill this form." },
  testimonials: { label: "Testimonials", help: "Real quotes you have permission to publish." },
  trustedBy: { label: "Customers you can name", help: "Company names you are allowed to show." },
  metrics: { label: "Numbers you can back up", help: "Each needs a short note on where it comes from." },
  certifications: { label: "Certifications", help: "Only ones you actually hold." },
  proofAttested: { label: "These are accurate and I'm allowed to show them publicly.", help: "Required when you add any proof above." },
  faq: { label: "Frequently asked questions", help: "Your own questions and answers." },
  objections: { label: "What do buyers worry about?", help: "Used for: FAQ and reassurance copy.", example: "Price, data security, switching from spreadsheets" },
  socialLinks: { label: "Social links", help: "Shown in the footer." },
  phone: { label: "Phone", help: "Shown in the contact section." },
  companyAddress: { label: "Company address", help: "Shown in the footer and legal pages." },
  legal: { label: "Privacy and terms", help: "Link your own pages or use templates later." },
  trafficSources: { label: "Where will visitors come from?", help: "Used for: SEO and message focus." },
  targetKeywords: { label: "Search terms", help: "Up to 10 phrases people would search for." },
  campaignMessage: { label: "Campaign message", help: "If you are running a campaign, the line it uses." },
} as const

export const BRIEF_OPTION_LABELS = {
  productType: {
    SOFTWARE_SAAS: "Software / SaaS",
    MOBILE_APP: "Mobile app",
    SERVICE: "Service",
    PHYSICAL_PRODUCT: "Physical product",
    MARKETPLACE: "Marketplace",
    EDUCATION_CONTENT: "Course or content",
    OTHER: "Something else",
  },
  availability: {
    LIVE: "Yes, it's live",
    BETA: "In beta",
    LAUNCHING_SOON: "Launching soon",
  },
  primaryGoal: {
    SALES: "Sell directly",
    DEMO_BOOKINGS: "Book demos",
    FREE_TRIAL: "Start a free trial",
    APP_DOWNLOADS: "Download the app",
    INQUIRIES: "Get inquiries",
    EMAIL_SIGNUPS: "Grow an email list",
    WAITLIST: "Join a waitlist",
  },
  audienceSegment: { B2B: "Businesses", B2C: "Consumers", BOTH: "Both" },
  techLevel: { LOW: "Not technical", MEDIUM: "Somewhat technical", HIGH: "Very technical" },
  siteType: { SINGLE_PAGE: "One page", MULTI_PAGE: "Several pages", AI_DECIDES: "Let AI decide" },
  pricingMode: {
    SHOW_PLANS: "Show my plans",
    CONTACT_SALES: "Contact sales",
    FREE: "It's free",
    HIDE: "Don't show pricing",
  },
  priceInterval: { MONTHLY: "per month", YEARLY: "per year", ONE_TIME: "one time", CUSTOM: "custom" },
  ctaType: { URL: "Link", EMAIL: "Email me", FORM: "Form on the site" },
  tone: {
    PROFESSIONAL: "Professional",
    FRIENDLY: "Friendly",
    TECHNICAL: "Technical",
    PREMIUM: "Premium",
    PLAYFUL: "Playful",
    BOLD: "Bold",
    CALM: "Calm",
  },
  legalMode: {
    LINK_OWN: "Link my own pages",
    GENERATE_TEMPLATE: "Use templates",
    NONE: "No legal pages",
  },
  trafficSource: {
    GOOGLE_SEARCH: "Google search",
    ADS: "Paid ads",
    LINKEDIN: "LinkedIn",
    EMAIL: "Email",
    SOCIAL: "Social media",
    DIRECT_REFERRAL: "Word of mouth",
    OTHER: "Other",
  },
  socialNetwork: {
    linkedin: "LinkedIn",
    x: "X",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "YouTube",
    github: "GitHub",
    other: "Other",
  },
} as const

export const BRIEF_SOURCE_LABELS = {
  user: "You",
  imported: "Suggested from your source",
  researched: "Researched",
  assumed: "AI assumed",
  default: "Default",
} as const

export const BRIEF_UI_COPY = {
  modalTitle: "Tell us about your product",
  editTitle: "Edit your brief",
  quickLabel: "Quick",
  fullLabel: "Full",
  back: "Back",
  continue: "Continue",
  skipStep: "Skip — AI will handle this",
  createProject: "Create project",
  saveChanges: "Save changes",
  saving: "Saving…",
  saved: "Saved",
  draftSaved: "Draft saved",
  required: "Required",
  optional: "Optional",
  letAiDecide: "Let AI decide",
  aiWillDecide: "AI will decide",
  suggested: "Suggested",
  accept: "Accept",
  add: "Add",
  remove: "Remove",
  moveUp: "Move up",
  moveDown: "Move down",
  quickSummaryTitle: "That's all we need",
  quickSummary: "We'll decide the rest. You'll review our assumptions before anything is built.",
  addMoreDetails: "Add more details (optional)",
  startFaster: "Start faster",
  startFasterHelp: "Paste notes, give a link or upload a document and we'll fill in what we can.",
  prefillTabs: { text: "Paste text", url: "Website URL", doc: "Upload document" },
  fillFromThis: "Fill from this",
  prefillWorking: "Reading it…",
  prefillFailed: "Couldn't read that, fill it in below.",
  cancel: "Cancel",
  conflict: "This draft changed in another tab. Reload it?",
  reload: "Reload",
  continueDraft: "Continue your draft",
  startNew: "Start new",
  eligibility: "You can fill this in now and save it; you'll need credits to generate.",
  upgrade: "Get credits",
  rateLimited: "You're going a bit fast. Your draft is saved; try again shortly.",
  proofImportedConfirm: "This is accurate and I can show it",
  editSavedNeedsRegenerate: "Saved. Regenerate to apply these changes.",
  publicEmailNote: "Visible on your site.",
  privateEmailNote: "Not shown on your site.",
} as const

export const BRIEF_OMITTED_COPY = {
  pricing: "Pricing (no plans given)",
  testimonials: "Testimonials (none provided)",
  trustedBy: "Customer logos (none provided)",
  metrics: "Stats (none provided)",
  certifications: "Certifications (none provided)",
  socialLinks: "Social links (none provided)",
  logo: "Logo (a text wordmark is used instead)",
  phone: "Phone number (none provided)",
  companyAddress: "Address (none provided)",
  ctaSecondary: "Second button (none provided)",
  campaignMessage: "Campaign message (none provided)",
  assumedDropped: "(we couldn't draft this safely)",
} as const

export const BRIEF_WARNING_COPY = {
  launchingSoonGoal: "Your product isn't live yet. A waitlist usually works better than this goal until launch.",
  appDownloadsNeedsLink: "App downloads need a link button that opens your app store page.",
  plansMissing: "You chose to show plans but haven't added any. Pricing will be hidden.",
  legalNotGenerated: "Legal pages are not generated yet. Link your own pages if you need them now.",
  formNotAvailable: "Forms on the site aren't available yet. Use a link or email button instead.",
} as const

export const BRIEF_PANEL_COPY = {
  title: "Brief",
  editBrief: "Edit brief",
  needsConfirmation: "Needs your confirmation",
  showAll: "Show all",
  omittedTitle: "We left out",
  warningsTitle: "Worth a look",
  reviewBanner: "Review your brief before we build",
  reviewHelp: "We filled a few gaps. Confirm or remove anything marked as a claim, then approve.",
  approve: "Approve and continue",
  confirm: "Confirm",
  edit: "Edit",
  remove: "Remove",
  resolving: "Reading your brief…",
  staleBanner: "Your brief changed since this version was generated. Regenerate to apply it.",
  resolveNotice: "We couldn't draft suggestions this time, so those parts are left out. You can add them yourself.",
  competitorNote: "Competitor analysis, not research",
  claimNote: "Claim — needs your confirmation",
} as const
