export const QUEUES = {
  CORPUS_INGEST: "corpus.ingest",
  VALIDATE_MAIN: "validateMain",
  VALIDATE: "validate",
  VALIDATION_CLEANUP: "validationCleanup",
  SCAN: "scan",
  GENERATE: "generate",
  DEPLOY: "deploy",
  WEBHOOK: "webhook",
  EMAIL: "email",
  DOMAIN_VERIFY: "domainVerify",
  CREDIT_RESET: "creditReset",
  SCORE: "score",
  SEO_AUDIT: "seoAudit",
  AUTO_RELOAD: "autoReload",
  EXPIRE_CACHE: "expireCache",
  RESEARCH_PDF: "researchPdf",
  // BullMQ rejects ":" in queue names.
  DEPLOY_RUN: "deployRun",
  DEPLOY_GC: "deployGc",
  DEPLOY_REAPER: "deployReaper",
  DEPLOY_KVS_RECONCILE: "deployKvsReconcile",
  DEPLOY_DOMAIN_RECONCILE: "deployDomainReconcile",
  DEPLOY_DOMAIN_HEALTHCHECK: "deployDomainHealthcheck",
  DEPLOY_DOMAIN_GC: "deployDomainGc",
  MEDIA_PROCESS: "mediaProcess",
  MEDIA_GC: "mediaGc",
} as const;

export type QueueName = (typeof QUEUES)[keyof typeof QUEUES];
