ALTER TYPE "ScanType" ADD VALUE IF NOT EXISTS 'REPLICATION_TARGET';

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "replicationSourceUrl" TEXT;
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "replicationFreeCorrectionUsed" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "freeReplicationUsed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "freeReplicationUsedAt" TIMESTAMP(3);
